apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backup-operator
  template:
    metadata:
      labels:
        app: backup-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "backup-operator" }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
