name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest tests/unit
  e2e:
    runs-on: ubuntu-latest
    needs: lint-unit
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.8.0
      - run: helm dependency update charts/backup-operator
      - run: bash tests/e2e/test_backup_flow_kind.sh
  chart-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - run: helm lint charts/backup-operator
