name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: docker build -t ghcr.io/you/backup-operator:${{ github.ref_name }} .
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/you/backup-operator:${{ github.ref_name }}
  chart-release:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
      - run: helm package charts/backup-operator
      - run: echo "Release chart as artifact or upload to chart repo"
